# Generated by Django 3.1.7 on 2021-04-12 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210310_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_email',
            field=models.EmailField(default='', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
