# Generated by Django 3.1.7 on 2021-03-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialholydaymodel',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='specialholydaymodel',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
