# Generated by Django 3.1.7 on 2021-03-07 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0002_auto_20210307_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofweek', models.PositiveSmallIntegerField(choices=[(0, '日曜'), (1, '月曜'), (2, '火曜'), (3, '水曜'), (4, '木曜'), (5, '金曜'), (6, '土曜')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
