# Generated by Django 3.1.7 on 2021-04-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0008_auto_20210405_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialholydaymodel',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='specialholydaymodel',
            name='start_date',
            field=models.DateField(),
        ),
    ]
