# Generated by Django 3.1.7 on 2021-04-12 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0009_auto_20210407_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='email',
            field=models.EmailField(default='', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
